### ISSUE TITLE
consulta por error de System.FormatException:

### ISSUE THREAD

**Issue by sawiiii** [RodrigoToroIcarte/IIC2113-2023-1#104]
Hola!, desde la primera entrega que tengo un método para entregar el damage de una carta pero ahora me empezó a arrojar el siguiente error: 
`Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
`
Revise el código y es donde me están saltando todos los tests con efectos de reversals y no tengo idea de como podría arreglarlo

De antemano muchas gracias y quedo atento

**Comment by RodrigoToroIcarte** [comment]
No tengo ni la menor idea ¯\\\_(ツ)\_/¯

Si me mandas tu código te podría ayudar.

**Comment by RodrigoToroIcarte** [comment]
(mándame solo las partes que parezcan relevantes para arreglar el error)
